server:
  port: 8081
  servlet:
    context-path: /client/api

spring:
  application.name: client-hujjat-business

logging:
  level:
    root: INFO
    uz.realsoft.clienthujjatbusiness: DEBUG

project:
  template-create-url: https://business.hujjat.uz/api/template/create
  document-create-url: https://business.hujjat.uz/api/document/create
  doc-key: nXCAnCp2S4A
